name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: igorbaratta/nbit
    env:
      CC: clang-10
      CXX: clang++-10
    steps:
    - uses: actions/checkout@v2
    - name: Cmake and Build
      run: |
          mkdir build 
          cd build 
          cmake .. 
          make
    - name: Build and run C++ unit tests
      run: |
          cd build 
          ctest -C Release -T test --output-on-failure
