name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake and build
      run: mkdir build && cd build && cmake .. && make
    - name: run tests
      run: |
            cd tests/
            source run_all.sh
    
